[package]
name = "royalty_pool"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.fm)"]

[dependencies]
hikida = { git = "https://github.com/unconfirmedlabs/hikida.git", rev = "c91d6a0f536a5f1457b342a8838fc1d7ba09212e" }
share = { git = "https://github.com/misofm/share.git", rev = "6ac1dbf022e74957c5ec15ecf95890e28889cd62" }
